language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버 Home
cache:
  directories:
    - '$Home/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r demo1 *
  - mkdir -p deploy
  - mv demo1.zip deploy/demo1.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: springboot-demo-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근 private으로
    local_dir: deploy # before_deploy에서 생성한 디랙토리
    wait-until-deployed: true

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - bjkim3671@gmail.com
